services:
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    image: immobot-bot:latest
    env_file:
      - ./bot/.env
    volumes:
      - ./data:/app/data

  crawler:
    build: 
      context: .
      dockerfile: ./crawler/Dockerfile
    image: immobot-crawler:latest
    env_file:
      - ./crawler/.env
    volumes:
      - ./data:/app/data

